### ISSUE TITLE
44010 should be 44100

### ISSUE THREAD

**Issue by thiemowmde** [ClockworkChilli/r3v3rs3_it#1]
My Chrome complains and the script crashs. Looks like an easy fix.

**Comment by ClockworkChilli** [comment]
Of course, you're right. I've managed to type it 4 times without realizing.

Thanks :)

**Comment by ClockworkChilli** [comment]
By the way, I hadn't seen it crash on any machine where I've tried it, but it may be worth filing a Chrome bug, as it really shouldn't have crashed.

I checked the spec of OfflineAudioContext and it says: "An implementation must support sample-rates in at least the range 22050 to 96000."

No mention of  having to be a multiple of 22050, even though obviously that's what I meant to do in this case.
